# libhaze patch cancel: sections 10 to 17
# 10. include/haze/results.hpp: ResultCancelled definition
# 11. include/haze.h: aborted flag in CallbackDataFile and CancelTransfer declaration
# 12. include/haze/console_main_loop.hpp: transfer cancellation consumer and CancelTransfer
# 13. source/haze.cpp: CancelTransfer implementation (deadlock-free Exit)
# 14. include/haze/ptp_responder.hpp: m_reactor and WriteCallbackFile aborted parameter
# 15. source/ptp_responder.cpp: HandleRequest ResultCancelled handling and WriteCallbackFile forwarding
# 16. source/usb_session.cpp: UsbError_UrbCancelled to ResultCancelled translation
# 17. source/ptp_responder_ptp_operations.cpp: incomplete file deletion, aborted cb, and reactor reset

# --- 10. include/haze/results.hpp : ResultCancelled --------------------------
if(EXISTS "include/haze/results.hpp")
    file(READ "include/haze/results.hpp" src)
    string(FIND "${src}" "R_DEFINE_ERROR_RESULT(Cancelled," find_cancelled)
    if(NOT find_cancelled EQUAL -1)
        message(STATUS "[libhaze-patch] results.hpp already patched")
    else()
        set(res_old "    R_DEFINE_ERROR_RESULT(DepthSpecified,        18);\n\n}")
        set(res_new "    R_DEFINE_ERROR_RESULT(DepthSpecified,        18);\n    /* sphaira: cancelled MTP transfer */\n    R_DEFINE_ERROR_RESULT(Cancelled,             19);\n\n}")
        string(REPLACE "${res_old}" "${res_new}" src "${src}")
        string(FIND "${src}" "R_DEFINE_ERROR_RESULT(Cancelled," find_cancelled_after)
        if(find_cancelled_after EQUAL -1)
            message(FATAL_ERROR "[libhaze-patch] failed to apply ResultCancelled patch to results.hpp")
        endif()
        file(WRITE "include/haze/results.hpp" "${src}")
        message(STATUS "[libhaze-patch] applied results.hpp ResultCancelled patch")
    endif()
else()
    message(FATAL_ERROR "[libhaze-patch] include/haze/results.hpp not found")
endif()

# --- 11. include/haze.h : CallbackDataFile aborted flag & CancelTransfer -----
if(EXISTS "include/haze.h")
    file(READ "include/haze.h" src)
    string(REPLACE "\n/* sphaira: clear transfer cancellation signal */\nvoid ClearTransferCancel();" "" src "${src}")
    string(REPLACE "void ClearTransferCancel();\n" "" src "${src}")

    string(FIND "${src}" "bool aborted;" find_aborted)
    string(FIND "${src}" "void CancelTransfer();" find_cancel_decl)
    string(FIND "${src}" "void ClearTransferCancel();" find_clear_decl)
    if(NOT find_aborted EQUAL -1 AND NOT find_cancel_decl EQUAL -1 AND find_clear_decl EQUAL -1)
        file(WRITE "include/haze.h" "${src}")
        message(STATUS "[libhaze-patch] haze.h cancel already patched")
    else()
        set(haze_h_file_old "typedef struct {\n    char filename[FS_MAX_PATH];\n} CallbackDataFile;")
        set(haze_h_file_new "typedef struct {\n    char filename[FS_MAX_PATH];\n    /* sphaira: true if the transfer was aborted/cancelled. */\n    bool aborted;\n} CallbackDataFile;")
        string(REPLACE "${haze_h_file_old}" "${haze_h_file_new}" src "${src}")

        set(haze_h_decl_old "bool Initialize(Callback callback, int prio, int cpuid, const FsEntries& entries);\nvoid Exit();\n\n} // namespace haze")
        set(haze_h_decl_new "bool Initialize(Callback callback, int prio, int cpuid, const FsEntries& entries);\nvoid Exit();\n/* sphaira: cancel current active file transfer */\nvoid CancelTransfer();\n\n} // namespace haze")
        string(REPLACE "${haze_h_decl_old}" "${haze_h_decl_new}" src "${src}")

        string(FIND "${src}" "bool aborted;" find_aborted_after)
        string(FIND "${src}" "void CancelTransfer();" find_cancel_decl_after)
        string(FIND "${src}" "void ClearTransferCancel();" find_clear_decl_after)
        if(find_aborted_after EQUAL -1 OR find_cancel_decl_after EQUAL -1 OR NOT find_clear_decl_after EQUAL -1)
            message(FATAL_ERROR "[libhaze-patch] failed to apply cancel patch to haze.h")
        endif()
        file(WRITE "include/haze.h" "${src}")
        message(STATUS "[libhaze-patch] applied haze.h cancel patch")
    endif()
else()
    message(FATAL_ERROR "[libhaze-patch] include/haze.h not found")
endif()

# --- 12. include/haze/console_main_loop.hpp : cancel consumer & CancelTransfer -
if(EXISTS "include/haze/console_main_loop.hpp")
    file(READ "include/haze/console_main_loop.hpp" src)
    set(cml_clear_old "            void CancelTransfer() {\n                ueventSignal(&m_transfer_cancel_event);\n            }\n\n            void ClearTransferCancel() {\n                ueventClear(&m_transfer_cancel_event);\n                m_event_reactor.SetResult(ResultSuccess());\n            }")
    set(cml_clear_new "            void CancelTransfer() {\n                ueventSignal(&m_transfer_cancel_event);\n            }")
    string(REPLACE "${cml_clear_old}" "${cml_clear_new}" src "${src}")

    string(FIND "${src}" "m_transfer_cancel_event" find_cancel_event)
    string(FIND "${src}" "void CancelTransfer()" find_cancel_fn)
    string(FIND "${src}" "void ClearTransferCancel()" find_clear_fn)
    if(NOT find_cancel_event EQUAL -1 AND NOT find_cancel_fn EQUAL -1 AND find_clear_fn EQUAL -1)
        file(WRITE "include/haze/console_main_loop.hpp" "${src}")
        message(STATUS "[libhaze-patch] console_main_loop.hpp already patched")
    else()
        set(cml_members_old "            Thread m_thread{};\n            UEvent m_cancel_event{};\n            EventReactor m_event_reactor{};\n\n        public:\n            explicit ConsoleMainLoop(Callback callback, int prio, int cpuid, const FsEntries& entries)\n            : m_callback{callback}, m_prio{prio}, m_cpuid{cpuid}, m_entries{entries} {\n                /* Create cancel event. */\n                ueventCreate(&m_cancel_event, false);\n\n                /* Clear the event reactor. */\n                m_event_reactor.SetResult(ResultSuccess());\n                m_event_reactor.AddConsumer(this, waiterForUEvent(&m_cancel_event));\n\n                /* Create and start thread. */\n                threadCreate(&m_thread, thread_func, this, nullptr, 1024*64, prio, cpuid);\n                threadStart(&m_thread);\n            }")
        set(cml_members_new "            struct TransferCancelConsumer final : EventConsumer {\n                EventReactor* reactor{nullptr};\n                void ProcessEvent() override {\n                    if (reactor && reactor->GetResult() == ResultSuccess()) {\n                        reactor->SetResult(haze::ResultCancelled());\n                    }\n                }\n            };\n            Thread m_thread{};\n            UEvent m_cancel_event{};\n            UEvent m_transfer_cancel_event{};\n            TransferCancelConsumer m_transfer_cancel_consumer{};\n            EventReactor m_event_reactor{};\n\n        public:\n            explicit ConsoleMainLoop(Callback callback, int prio, int cpuid, const FsEntries& entries)\n            : m_callback{callback}, m_prio{prio}, m_cpuid{cpuid}, m_entries{entries} {\n                /* Create cancel event. */\n                ueventCreate(&m_cancel_event, false);\n                ueventCreate(&m_transfer_cancel_event, true);\n\n                /* Clear the event reactor. */\n                m_event_reactor.SetResult(ResultSuccess());\n                m_event_reactor.AddConsumer(this, waiterForUEvent(&m_cancel_event));\n                m_transfer_cancel_consumer.reactor = std::addressof(m_event_reactor);\n                m_event_reactor.AddConsumer(std::addressof(m_transfer_cancel_consumer), waiterForUEvent(&m_transfer_cancel_event));\n\n                /* Create and start thread. */\n                threadCreate(&m_thread, thread_func, this, nullptr, 1024*64, prio, cpuid);\n                threadStart(&m_thread);\n            }")
        string(REPLACE "${cml_members_old}" "${cml_members_new}" src "${src}")

        set(cml_fn_old "            ~ConsoleMainLoop() {\n                ueventSignal(&m_cancel_event);\n                threadWaitForExit(&m_thread);\n                threadClose(&m_thread);\n            }\n\n        public:\n            void RunApplication() {")
        set(cml_fn_new "            ~ConsoleMainLoop() {\n                ueventSignal(&m_cancel_event);\n                threadWaitForExit(&m_thread);\n                threadClose(&m_thread);\n            }\n\n            void CancelTransfer() {\n                ueventSignal(&m_transfer_cancel_event);\n            }\n\n        public:\n            void RunApplication() {")
        string(REPLACE "${cml_fn_old}" "${cml_fn_new}" src "${src}")

        string(FIND "${src}" "m_transfer_cancel_event" find_cancel_event_after)
        string(FIND "${src}" "void CancelTransfer()" find_cancel_fn_after)
        string(FIND "${src}" "void ClearTransferCancel()" find_clear_fn_after)
        if(find_cancel_event_after EQUAL -1 OR find_cancel_fn_after EQUAL -1 OR NOT find_clear_fn_after EQUAL -1)
            message(FATAL_ERROR "[libhaze-patch] failed to apply cancel patch to console_main_loop.hpp")
        endif()
        file(WRITE "include/haze/console_main_loop.hpp" "${src}")
        message(STATUS "[libhaze-patch] applied console_main_loop.hpp cancel patch")
    endif()
else()
    message(FATAL_ERROR "[libhaze-patch] include/haze/console_main_loop.hpp not found")
endif()

# --- 13. source/haze.cpp : CancelTransfer (deadlock-free Exit) ---------------
if(EXISTS "source/haze.cpp")
    file(READ "source/haze.cpp" src)
    set(haze_cpp_prev "void Exit() {\n    std::scoped_lock lock{g_mutex};\n    if (!g_haze) {\n        return;\n    }\n\n    /* this will block until thread exit. */\n    g_haze.reset();\n}\n\nvoid CancelTransfer() {\n    std::scoped_lock lock{g_mutex};\n    if (g_haze) {\n        g_haze->CancelTransfer();\n    }\n}\n\nvoid ClearTransferCancel() {\n    std::scoped_lock lock{g_mutex};\n    if (g_haze) {\n        g_haze->ClearTransferCancel();\n    }\n}\n\n} // namespace haze")
    set(haze_cpp_target "void Exit() {\n    std::unique_ptr<haze::ConsoleMainLoop> haze_to_destroy;\n    {\n        std::scoped_lock lock{g_mutex};\n        if (!g_haze) {\n            return;\n        }\n\n        /* move instance so g_mutex is released before blocking on thread exit. */\n        haze_to_destroy = std::move(g_haze);\n    }\n}\n\nvoid CancelTransfer() {\n    std::scoped_lock lock{g_mutex};\n    if (g_haze) {\n        g_haze->CancelTransfer();\n    }\n}\n\n} // namespace haze")
    string(REPLACE "${haze_cpp_prev}" "${haze_cpp_target}" src "${src}")

    string(FIND "${src}" "void CancelTransfer()" find_cancel_impl)
    string(FIND "${src}" "haze_to_destroy = std::move(g_haze);" find_exit_move)
    string(FIND "${src}" "void ClearTransferCancel()" find_clear_impl)
    if(NOT find_cancel_impl EQUAL -1 AND NOT find_exit_move EQUAL -1 AND find_clear_impl EQUAL -1)
        file(WRITE "source/haze.cpp" "${src}")
        message(STATUS "[libhaze-patch] haze.cpp cancel already patched")
    else()
        set(haze_cpp_old "void Exit() {\n    std::scoped_lock lock{g_mutex};\n    if (!g_haze) {\n        return;\n    }\n\n    /* this will block until thread exit. */\n    g_haze.reset();\n}\n\n} // namespace haze")
        set(haze_cpp_new "void Exit() {\n    std::unique_ptr<haze::ConsoleMainLoop> haze_to_destroy;\n    {\n        std::scoped_lock lock{g_mutex};\n        if (!g_haze) {\n            return;\n        }\n\n        /* move instance so g_mutex is released before blocking on thread exit. */\n        haze_to_destroy = std::move(g_haze);\n    }\n}\n\nvoid CancelTransfer() {\n    std::scoped_lock lock{g_mutex};\n    if (g_haze) {\n        g_haze->CancelTransfer();\n    }\n}\n\n} // namespace haze")
        string(REPLACE "${haze_cpp_old}" "${haze_cpp_new}" src "${src}")
        string(FIND "${src}" "void CancelTransfer()" find_cancel_impl_after)
        string(FIND "${src}" "haze_to_destroy = std::move(g_haze);" find_exit_move_after)
        string(FIND "${src}" "void ClearTransferCancel()" find_clear_impl_after)
        if(find_cancel_impl_after EQUAL -1 OR find_exit_move_after EQUAL -1 OR NOT find_clear_impl_after EQUAL -1)
            message(FATAL_ERROR "[libhaze-patch] failed to apply CancelTransfer patch to haze.cpp")
        endif()
        file(WRITE "source/haze.cpp" "${src}")
        message(STATUS "[libhaze-patch] applied haze.cpp CancelTransfer patch")
    endif()
else()
    message(FATAL_ERROR "[libhaze-patch] source/haze.cpp not found")
endif()

# --- 14. include/haze/ptp_responder.hpp : m_reactor & WriteCallbackFile aborted
if(EXISTS "include/haze/ptp_responder.hpp")
    file(READ "include/haze/ptp_responder.hpp" src)
    string(FIND "${src}" "EventReactor *m_reactor" find_reactor)
    string(FIND "${src}" "bool aborted = false" find_aborted_param)
    if(NOT find_reactor EQUAL -1 AND NOT find_aborted_param EQUAL -1)
        message(STATUS "[libhaze-patch] ptp_responder.hpp cancel already patched")
    else()
        set(resp_h_members_old "        private:\n            Callback m_callback;\n            AsyncUsbServer m_usb_server;\n            std::vector<FsEntry> m_fs_entries;")
        set(resp_h_members_new "        private:\n            Callback m_callback;\n            AsyncUsbServer m_usb_server;\n            EventReactor *m_reactor{nullptr};\n            std::vector<FsEntry> m_fs_entries;")
        string(REPLACE "${resp_h_members_old}" "${resp_h_members_new}" src "${src}")

        set(resp_h_cb_old "            void WriteCallbackSession(CallbackType type);\n            void WriteCallbackFile(CallbackType type, const char* name);\n            void WriteCallbackRename(CallbackType type, const char* name, const char* newname);")
        set(resp_h_cb_new "            void WriteCallbackSession(CallbackType type);\n            void WriteCallbackFile(CallbackType type, const char* name, bool aborted = false);\n            void WriteCallbackRename(CallbackType type, const char* name, const char* newname);")
        string(REPLACE "${resp_h_cb_old}" "${resp_h_cb_new}" src "${src}")

        string(FIND "${src}" "EventReactor *m_reactor" find_reactor_after)
        string(FIND "${src}" "bool aborted = false" find_aborted_param_after)
        if(find_reactor_after EQUAL -1 OR find_aborted_param_after EQUAL -1)
            message(FATAL_ERROR "[libhaze-patch] failed to apply cancel patch to ptp_responder.hpp")
        endif()
        file(WRITE "include/haze/ptp_responder.hpp" "${src}")
        message(STATUS "[libhaze-patch] applied ptp_responder.hpp cancel patch")
    endif()
else()
    message(FATAL_ERROR "[libhaze-patch] include/haze/ptp_responder.hpp not found")
endif()

# --- 15. source/ptp_responder.cpp : HandleRequest & WriteCallbackFile --------
if(EXISTS "source/ptp_responder.cpp")
    file(READ "source/ptp_responder.cpp" src)
    set(resp_cpp_unconditional "            R_CATCH(haze::ResultCancelled) {\n                if (m_reactor) {\n                    m_reactor->SetResult(ResultSuccess());\n                }\n                R_TRY(this->WriteResponse(PtpResponseCode_TransactionCanceled));\n            }")
    set(resp_cpp_conditional "            R_CATCH(haze::ResultCancelled) {\n                if (m_reactor && m_reactor->GetResult() == haze::ResultCancelled()) {\n                    m_reactor->SetResult(ResultSuccess());\n                }\n                R_TRY(this->WriteResponse(PtpResponseCode_TransactionCanceled));\n            }")
    string(REPLACE "${resp_cpp_unconditional}" "${resp_cpp_conditional}" src "${src}")

    string(FIND "${src}" "m_reactor = reactor;" find_init_reactor)
    string(FIND "${src}" "m_reactor->GetResult() == haze::ResultCancelled()" find_guard_reactor)
    string(FIND "${src}" "PtpResponseCode_TransactionCanceled" find_trans_cancel)
    string(FIND "${src}" "data.file.aborted = aborted;" find_data_aborted)
    if(NOT find_init_reactor EQUAL -1 AND NOT find_guard_reactor EQUAL -1 AND NOT find_trans_cancel EQUAL -1 AND NOT find_data_aborted EQUAL -1)
        file(WRITE "source/ptp_responder.cpp" "${src}")
        message(STATUS "[libhaze-patch] ptp_responder.cpp cancel already patched")
    else()
        set(resp_cpp_init_old "    Result PtpResponder::Initialize(EventReactor *reactor, PtpObjectHeap *object_heap, const FsEntries& entries) {\n        m_object_heap = object_heap;")
        set(resp_cpp_init_new "    Result PtpResponder::Initialize(EventReactor *reactor, PtpObjectHeap *object_heap, const FsEntries& entries) {\n        m_reactor = reactor;\n        m_object_heap = object_heap;")
        string(REPLACE "${resp_cpp_init_old}" "${resp_cpp_init_new}" src "${src}")

        set(resp_cpp_handle_old "        R_TRY_CATCH(this->HandleRequestImpl()) {\n            R_CATCH(haze::ResultUnknownRequestType) {")
        set(resp_cpp_handle_new "        R_TRY_CATCH(this->HandleRequestImpl()) {\n            R_CATCH(haze::ResultCancelled) {\n                if (m_reactor && m_reactor->GetResult() == haze::ResultCancelled()) {\n                    m_reactor->SetResult(ResultSuccess());\n                }\n                R_TRY(this->WriteResponse(PtpResponseCode_TransactionCanceled));\n            }\n            R_CATCH(haze::ResultUnknownRequestType) {")
        string(REPLACE "${resp_cpp_handle_old}" "${resp_cpp_handle_new}" src "${src}")

        set(resp_cpp_cb_old "    void PtpResponder::WriteCallbackFile(CallbackType type, const char* name) {\n        if (!m_callback) {\n            return;\n        }\n        CallbackData data{type};\n        std::strncpy(data.file.filename, FixName(name), sizeof(data.file.filename)-1);\n        m_callback(&data);\n    }")
        set(resp_cpp_cb_new "    void PtpResponder::WriteCallbackFile(CallbackType type, const char* name, bool aborted) {\n        if (!m_callback) {\n            return;\n        }\n        CallbackData data{type};\n        std::strncpy(data.file.filename, FixName(name), sizeof(data.file.filename)-1);\n        data.file.aborted = aborted;\n        m_callback(&data);\n    }")
        string(REPLACE "${resp_cpp_cb_old}" "${resp_cpp_cb_new}" src "${src}")

        string(FIND "${src}" "m_reactor = reactor;" find_init_reactor_after)
        string(FIND "${src}" "m_reactor->GetResult() == haze::ResultCancelled()" find_guard_reactor_after)
        string(FIND "${src}" "PtpResponseCode_TransactionCanceled" find_trans_cancel_after)
        string(FIND "${src}" "data.file.aborted = aborted;" find_data_aborted_after)
        if(find_init_reactor_after EQUAL -1 OR find_guard_reactor_after EQUAL -1 OR find_trans_cancel_after EQUAL -1 OR find_data_aborted_after EQUAL -1)
            message(FATAL_ERROR "[libhaze-patch] failed to apply cancel patch to ptp_responder.cpp")
        endif()
        file(WRITE "source/ptp_responder.cpp" "${src}")
        message(STATUS "[libhaze-patch] applied ptp_responder.cpp cancel patch")
    endif()
else()
    message(FATAL_ERROR "[libhaze-patch] source/ptp_responder.cpp not found")
endif()

# --- 16. source/usb_session.cpp : UsbError_UrbCancelled to ResultCancelled ----
if(EXISTS "source/usb_session.cpp")
    file(READ "source/usb_session.cpp" src)
    string(FIND "${src}" "parse_res == 0x748C" find_urb_cancel)
    if(NOT find_urb_cancel EQUAL -1)
        message(STATUS "[libhaze-patch] usb_session.cpp cancel already patched")
    else()
        set(usb_sess_old "    Result UsbSession::GetTransferResult(UsbSessionEndpoint ep, u32 urb_id, u32 *out_transferred_size) {\n        UsbDsReportData report_data;\n\n        R_TRY(eventClear(std::addressof(m_endpoints[ep]->CompletionEvent)));\n        R_TRY(usbDsEndpoint_GetReportData(m_endpoints[ep], std::addressof(report_data)));\n        R_TRY(usbDsParseReportData(std::addressof(report_data), urb_id, nullptr, out_transferred_size));\n\n        R_SUCCEED();\n    }")
        set(usb_sess_new "    Result UsbSession::GetTransferResult(UsbSessionEndpoint ep, u32 urb_id, u32 *out_transferred_size) {\n        UsbDsReportData report_data;\n\n        R_TRY(eventClear(std::addressof(m_endpoints[ep]->CompletionEvent)));\n        R_TRY(usbDsEndpoint_GetReportData(m_endpoints[ep], std::addressof(report_data)));\n        const Result parse_res = usbDsParseReportData(std::addressof(report_data), urb_id, nullptr, out_transferred_size);\n        if (parse_res == 0x748C) {\n            R_THROW(haze::ResultCancelled());\n        }\n        R_RETURN(parse_res);\n    }")
        string(REPLACE "${usb_sess_old}" "${usb_sess_new}" src "${src}")
        string(FIND "${src}" "parse_res == 0x748C" find_urb_cancel_after)
        if(find_urb_cancel_after EQUAL -1)
            message(FATAL_ERROR "[libhaze-patch] failed to apply cancel patch to usb_session.cpp")
        endif()
        file(WRITE "source/usb_session.cpp" "${src}")
        message(STATUS "[libhaze-patch] applied usb_session.cpp cancel patch")
    endif()
else()
    message(FATAL_ERROR "[libhaze-patch] source/usb_session.cpp not found")
endif()

# --- 17. source/ptp_responder_ptp_operations.cpp : delete partial file & aborted cb
if(EXISTS "source/ptp_responder_ptp_operations.cpp")
    file(READ "source/ptp_responder_ptp_operations.cpp" src)
    set(ops_read_prev "        bool transfer_success = false;\n        WriteCallbackFile(CallbackType_ReadBegin, obj->GetName());\n        ON_SCOPE_EXIT { WriteCallbackFile(CallbackType_ReadEnd, obj->GetName(), !transfer_success); };")
    set(ops_read_upgrade "        if (m_reactor && m_reactor->GetResult() == haze::ResultCancelled()) {\n            m_reactor->SetResult(ResultSuccess());\n        }\n\n        bool transfer_success = false;\n        WriteCallbackFile(CallbackType_ReadBegin, obj->GetName());\n        ON_SCOPE_EXIT { WriteCallbackFile(CallbackType_ReadEnd, obj->GetName(), !transfer_success); };")
    string(REPLACE "${ops_read_prev}" "${ops_read_upgrade}" src "${src}")

    set(ops_write_prev "        /* Lock the object as a file. */\n        FsFile file;\n        R_TRY(Fs(obj).OpenFile(obj->GetName(), FsOpenMode_Write | FsOpenMode_Append, std::addressof(file)));\n\n        bool transfer_success = false;\n\n        /* Ensure we maintain a clean state on exit. */\n        ON_SCOPE_EXIT {\n            Fs(obj).CloseFile(std::addressof(file));\n            if (!transfer_success) {\n                Fs(obj).DeleteFile(obj->GetName());\n                m_object_database.DeleteObject(obj);\n            }\n        };")
    set(ops_write_upgrade "        if (m_reactor && m_reactor->GetResult() == haze::ResultCancelled()) {\n            m_reactor->SetResult(ResultSuccess());\n        }\n\n        /* Lock the object as a file. */\n        FsFile file;\n        R_TRY(Fs(obj).OpenFile(obj->GetName(), FsOpenMode_Write | FsOpenMode_Append, std::addressof(file)));\n\n        bool transfer_success = false;\n\n        /* Ensure we maintain a clean state on exit. */\n        ON_SCOPE_EXIT {\n            Fs(obj).CloseFile(std::addressof(file));\n            if (!transfer_success) {\n                Fs(obj).DeleteFile(obj->GetName());\n                m_object_database.DeleteObject(obj);\n            }\n        };")
    string(REPLACE "${ops_write_prev}" "${ops_write_upgrade}" src "${src}")

    string(FIND "${src}" "!transfer_success" find_transfer_success)
    string(FIND "${src}" "transfer_success && offset != file_size" find_trunc_check)
    string(FIND "${src}" "WriteCallbackFile(CallbackType_WriteEnd, obj->GetName(), !transfer_success);" find_write_end_aborted)
    string(FIND "${src}" "WriteCallbackFile(CallbackType_ReadEnd, obj->GetName(), !transfer_success);" find_read_end_aborted)
    string(FIND "${src}" "if (m_reactor && m_reactor->GetResult() == haze::ResultCancelled())" find_clear_reactor)
    if(NOT find_transfer_success EQUAL -1 AND NOT find_trunc_check EQUAL -1 AND NOT find_write_end_aborted EQUAL -1 AND NOT find_read_end_aborted EQUAL -1 AND NOT find_clear_reactor EQUAL -1)
        file(WRITE "source/ptp_responder_ptp_operations.cpp" "${src}")
        message(STATUS "[libhaze-patch] ptp_responder_ptp_operations.cpp cancel already patched")
    else()
        set(ops_read_cancel_old "        WriteCallbackFile(CallbackType_ReadBegin, obj->GetName());\n        ON_SCOPE_EXIT { WriteCallbackFile(CallbackType_ReadEnd, obj->GetName()); };")
        set(ops_read_cancel_new "        if (m_reactor && m_reactor->GetResult() == haze::ResultCancelled()) {\n            m_reactor->SetResult(ResultSuccess());\n        }\n\n        bool transfer_success = false;\n        WriteCallbackFile(CallbackType_ReadBegin, obj->GetName());\n        ON_SCOPE_EXIT { WriteCallbackFile(CallbackType_ReadEnd, obj->GetName(), !transfer_success); };")
        string(REPLACE "${ops_read_cancel_old}" "${ops_read_cancel_new}" src "${src}")

        set(ops_read_ok_old "        /* Flush the data response. */\n        R_TRY(db.Commit());\n\n        /* Write the success response. */\n        R_RETURN(this->WriteResponse(PtpResponseCode_Ok));\n    }")
        set(ops_read_ok_new "        /* Flush the data response. */\n        R_TRY(db.Commit());\n\n        transfer_success = true;\n\n        /* Write the success response. */\n        R_RETURN(this->WriteResponse(PtpResponseCode_Ok));\n    }")
        string(REPLACE "${ops_read_ok_old}" "${ops_read_ok_new}" src "${src}")

        set(ops_write_clean_old "        /* Lock the object as a file. */\n        FsFile file;\n        R_TRY(Fs(obj).OpenFile(obj->GetName(), FsOpenMode_Write | FsOpenMode_Append, std::addressof(file)));\n\n        /* Ensure we maintain a clean state on exit. */\n        ON_SCOPE_EXIT { Fs(obj).CloseFile(std::addressof(file)); };")
        set(ops_write_clean_new "        if (m_reactor && m_reactor->GetResult() == haze::ResultCancelled()) {\n            m_reactor->SetResult(ResultSuccess());\n        }\n\n        /* Lock the object as a file. */\n        FsFile file;\n        R_TRY(Fs(obj).OpenFile(obj->GetName(), FsOpenMode_Write | FsOpenMode_Append, std::addressof(file)));\n\n        bool transfer_success = false;\n\n        /* Ensure we maintain a clean state on exit. */\n        ON_SCOPE_EXIT {\n            Fs(obj).CloseFile(std::addressof(file));\n            if (!transfer_success) {\n                Fs(obj).DeleteFile(obj->GetName());\n                m_object_database.DeleteObject(obj);\n            }\n        };")
        string(REPLACE "${ops_write_clean_old}" "${ops_write_clean_new}" src "${src}")

        set(ops_write_trunc_old "        /* Truncate the file to the received size. */\n        ON_SCOPE_EXIT{\n            if (offset != file_size) {\n                Fs(obj).SetFileSize(std::addressof(file), offset);\n            }\n        };\n\n        WriteCallbackFile(CallbackType_WriteBegin, obj->GetName());\n        ON_SCOPE_EXIT { WriteCallbackFile(CallbackType_WriteEnd, obj->GetName()); };")
        set(ops_write_trunc_new "        /* Truncate the file to the received size. */\n        ON_SCOPE_EXIT{\n            if (transfer_success && offset != file_size) {\n                Fs(obj).SetFileSize(std::addressof(file), offset);\n            }\n        };\n\n        WriteCallbackFile(CallbackType_WriteBegin, obj->GetName());\n        ON_SCOPE_EXIT { WriteCallbackFile(CallbackType_WriteEnd, obj->GetName(), !transfer_success); };")
        string(REPLACE "${ops_write_trunc_old}" "${ops_write_trunc_new}" src "${src}")

        set(ops_write_ok_old "        /* Write the success response. */\n        R_RETURN(this->WriteResponse(PtpResponseCode_Ok));\n    }\n\n    Result PtpResponder::DeleteObject(PtpDataParser &dp) {")
        set(ops_write_ok_new "        transfer_success = true;\n\n        /* Write the success response. */\n        R_RETURN(this->WriteResponse(PtpResponseCode_Ok));\n    }\n\n    Result PtpResponder::DeleteObject(PtpDataParser &dp) {")
        string(REPLACE "${ops_write_ok_old}" "${ops_write_ok_new}" src "${src}")

        string(FIND "${src}" "!transfer_success" find_transfer_success_after)
        string(FIND "${src}" "transfer_success && offset != file_size" find_trunc_check_after)
        string(FIND "${src}" "WriteCallbackFile(CallbackType_WriteEnd, obj->GetName(), !transfer_success);" find_write_end_aborted_after)
        string(FIND "${src}" "WriteCallbackFile(CallbackType_ReadEnd, obj->GetName(), !transfer_success);" find_read_end_aborted_after)
        string(FIND "${src}" "if (m_reactor && m_reactor->GetResult() == haze::ResultCancelled())" find_clear_reactor_after)
        if(find_transfer_success_after EQUAL -1 OR find_trunc_check_after EQUAL -1 OR find_write_end_aborted_after EQUAL -1 OR find_read_end_aborted_after EQUAL -1 OR find_clear_reactor_after EQUAL -1)
            message(FATAL_ERROR "[libhaze-patch] failed to apply cancel cleanup patch to ptp_responder_ptp_operations.cpp")
        endif()
        file(WRITE "source/ptp_responder_ptp_operations.cpp" "${src}")
        message(STATUS "[libhaze-patch] applied ptp_responder_ptp_operations.cpp cancel patch")
    endif()
else()
    message(FATAL_ERROR "[libhaze-patch] source/ptp_responder_ptp_operations.cpp not found")
endif()
