# libhaze patch cancel: sections 10 to 16
# 10. include/haze/results.hpp: ResultCancelled definition
# 11. include/haze.h: aborted flag in CallbackDataFile and CancelTransfer declaration
# 12. include/haze/console_main_loop.hpp: transfer cancellation consumer and CancelTransfer
# 13. source/haze.cpp: CancelTransfer implementation (deadlock-free Exit)
# 14. include/haze/ptp_responder.hpp: m_reactor and WriteCallbackFile aborted parameter
# 15. source/ptp_responder.cpp: HandleRequest ResultCancelled handling and WriteCallbackFile forwarding
# 16. include/haze/usb_session.hpp & source/usb_session.cpp: CancelEndpoint & ResultCancelled translation

# --- 10. include/haze/results.hpp : ResultCancelled & ResultTimeout ---------
if(EXISTS "include/haze/results.hpp")
    file(READ "include/haze/results.hpp" src)
    string(FIND "${src}" "R_DEFINE_ERROR_RESULT(Cancelled," find_cancelled)
    string(FIND "${src}" "R_DEFINE_ERROR_RESULT(Timeout," find_timeout)
    string(FIND "${src}" "operator==(Result lhs, Result rhs)" find_ops)
    if(NOT find_cancelled EQUAL -1 AND NOT find_timeout EQUAL -1 AND NOT find_ops EQUAL -1)
        message(STATUS "[libhaze-patch] results.hpp already patched")
    else()
        set(ops_code "\n\nnamespace ams {\n\n    constexpr ALWAYS_INLINE bool operator==(Result lhs, Result rhs) {\n        return lhs.GetValue() == rhs.GetValue();\n    }\n\n    constexpr ALWAYS_INLINE bool operator==(Result lhs, u32 rhs) {\n        return lhs.GetValue() == rhs;\n    }\n\n    constexpr ALWAYS_INLINE bool operator==(u32 lhs, Result rhs) {\n        return lhs == rhs.GetValue();\n    }\n\n    constexpr ALWAYS_INLINE bool operator==(Result lhs, int rhs) {\n        return lhs.GetValue() == static_cast<u32>(rhs);\n    }\n\n    constexpr ALWAYS_INLINE bool operator==(int lhs, Result rhs) {\n        return static_cast<u32>(lhs) == rhs.GetValue();\n    }\n\n}")
        set(res_both "    /* sphaira: cancelled MTP transfer */\n    R_DEFINE_ERROR_RESULT(Cancelled,             19);\n    /* sphaira: timeout during event wait */\n    R_DEFINE_ERROR_RESULT(Timeout,               20);\n\n}")

        string(FIND "${src}" "R_DEFINE_ERROR_RESULT(Cancelled," find_c)
        string(FIND "${src}" "R_DEFINE_ERROR_RESULT(Timeout," find_t)
        if(NOT find_c EQUAL -1 AND find_t EQUAL -1)
            set(res_prev "    /* sphaira: cancelled MTP transfer */\n    R_DEFINE_ERROR_RESULT(Cancelled,             19);\n\n}")
            string(REPLACE "${res_prev}" "${res_both}" src "${src}")
        elseif(find_c EQUAL -1)
            set(res_old "    R_DEFINE_ERROR_RESULT(DepthSpecified,        18);\n\n}")
            set(res_new "    R_DEFINE_ERROR_RESULT(DepthSpecified,        18);\n\n${res_both}")
            string(REPLACE "${res_old}" "${res_new}" src "${src}")
        endif()

        string(FIND "${src}" "operator==(Result lhs, Result rhs)" find_ops_check)
        if(find_ops_check EQUAL -1)
            set(res_tail "    R_DEFINE_ERROR_RESULT(Timeout,               20);\n\n}")
            string(REPLACE "${res_tail}" "${res_tail}${ops_code}" src "${src}")
        endif()

        string(FIND "${src}" "R_DEFINE_ERROR_RESULT(Cancelled," find_cancelled_after)
        string(FIND "${src}" "R_DEFINE_ERROR_RESULT(Timeout," find_timeout_after)
        string(FIND "${src}" "operator==(Result lhs, Result rhs)" find_ops_after)
        if(find_cancelled_after EQUAL -1 OR find_timeout_after EQUAL -1 OR find_ops_after EQUAL -1)
            message(FATAL_ERROR "[libhaze-patch] failed to apply ResultCancelled & ResultTimeout patch to results.hpp")
        endif()
        file(WRITE "include/haze/results.hpp" "${src}")
        message(STATUS "[libhaze-patch] applied results.hpp ResultCancelled & ResultTimeout patch")
    endif()

else()
    message(FATAL_ERROR "[libhaze-patch] include/haze/results.hpp not found")
endif()

# --- 11. include/haze.h : CallbackDataFile aborted flag & CancelTransfer -----
if(EXISTS "include/haze.h")
    file(READ "include/haze.h" src)
    string(REPLACE "\n/* sphaira: clear transfer cancellation signal */\nvoid ClearTransferCancel();" "" src "${src}")
    string(REPLACE "void ClearTransferCancel();\n" "" src "${src}")

    string(FIND "${src}" "bool aborted;" find_aborted)
    string(FIND "${src}" "void CancelTransfer();" find_cancel_decl)
    string(FIND "${src}" "bool IsRecovering();" find_recovering_decl)
    string(FIND "${src}" "void ClearRecovering();" find_clear_recovering_decl)
    string(FIND "${src}" "void ClearTransferCancel();" find_clear_decl)
    if(NOT find_aborted EQUAL -1 AND NOT find_cancel_decl EQUAL -1 AND NOT find_recovering_decl EQUAL -1 AND NOT find_clear_recovering_decl EQUAL -1 AND find_clear_decl EQUAL -1)
        file(WRITE "include/haze.h" "${src}")
        message(STATUS "[libhaze-patch] haze.h cancel already patched")
    else()
        set(haze_h_file_old "typedef struct {\n    char filename[FS_MAX_PATH];\n} CallbackDataFile;")
        set(haze_h_file_new "typedef struct {\n    char filename[FS_MAX_PATH];\n    /* sphaira: true if the transfer was aborted/cancelled. */\n    bool aborted;\n} CallbackDataFile;")
        string(REPLACE "${haze_h_file_old}" "${haze_h_file_new}" src "${src}")

        set(haze_h_decl_old "bool Initialize(Callback callback, int prio, int cpuid, const FsEntries& entries);\nvoid Exit();\n\n} // namespace haze")
        set(haze_h_decl_prev "bool Initialize(Callback callback, int prio, int cpuid, const FsEntries& entries);\nvoid Exit();\n/* sphaira: cancel current active file transfer */\nvoid CancelTransfer();\n\n} // namespace haze")
        set(haze_h_decl_new "bool Initialize(Callback callback, int prio, int cpuid, const FsEntries& entries);\nvoid Exit();\n/* sphaira: cancel current active file transfer */\nvoid CancelTransfer();\n/* sphaira: true during controlled USB session recovery */\nbool IsRecovering();\nvoid ClearRecovering();\n\n} // namespace haze")
        string(REPLACE "${haze_h_decl_prev}" "${haze_h_decl_new}" src "${src}")
        string(REPLACE "${haze_h_decl_old}" "${haze_h_decl_new}" src "${src}")

        string(FIND "${src}" "bool aborted;" find_aborted_after)
        string(FIND "${src}" "void CancelTransfer();" find_cancel_decl_after)
        string(FIND "${src}" "bool IsRecovering();" find_recovering_decl_after)
        string(FIND "${src}" "void ClearRecovering();" find_clear_recovering_decl_after)
        string(FIND "${src}" "void ClearTransferCancel();" find_clear_decl_after)
        if(find_aborted_after EQUAL -1 OR find_cancel_decl_after EQUAL -1 OR find_recovering_decl_after EQUAL -1 OR find_clear_recovering_decl_after EQUAL -1 OR NOT find_clear_decl_after EQUAL -1)
            message(FATAL_ERROR "[libhaze-patch] failed to apply cancel patch to haze.h")
        endif()
        file(WRITE "include/haze.h" "${src}")
        message(STATUS "[libhaze-patch] applied haze.h cancel patch")
    endif()
else()
    message(FATAL_ERROR "[libhaze-patch] include/haze.h not found")
endif()

# --- 12. include/haze/console_main_loop.hpp : cancel consumer & CancelTransfer -
if(EXISTS "include/haze/console_main_loop.hpp")
    file(READ "include/haze/console_main_loop.hpp" src)
    string(FIND "${src}" "#include <atomic>" find_atomic_include)
    if(find_atomic_include EQUAL -1)
        string(REPLACE "#include <haze/event_reactor.hpp>" "#include <atomic>\n#include <haze/event_reactor.hpp>" src "${src}")
    endif()

    set(cml_clear_old "            void CancelTransfer() {\n                ueventSignal(&m_transfer_cancel_event);\n            }\n\n            void ClearTransferCancel() {\n                ueventClear(&m_transfer_cancel_event);\n                m_event_reactor.SetResult(ResultSuccess());\n            }")
    set(cml_clear_new "            void CancelTransfer() {\n                ueventSignal(&m_transfer_cancel_event);\n            }")
    string(REPLACE "${cml_clear_old}" "${cml_clear_new}" src "${src}")

    set(cml_members_old "            Thread m_thread{};\n            UEvent m_cancel_event{};\n            EventReactor m_event_reactor{};\n\n        public:\n            explicit ConsoleMainLoop(Callback callback, int prio, int cpuid, const FsEntries& entries)\n            : m_callback{callback}, m_prio{prio}, m_cpuid{cpuid}, m_entries{entries} {\n                /* Create cancel event. */\n                ueventCreate(&m_cancel_event, false);\n\n                /* Clear the event reactor. */\n                m_event_reactor.SetResult(ResultSuccess());\n                m_event_reactor.AddConsumer(this, waiterForUEvent(&m_cancel_event));\n\n                /* Create and start thread. */\n                threadCreate(&m_thread, thread_func, this, nullptr, 1024*64, prio, cpuid);\n                threadStart(&m_thread);\n            }")
    set(cml_members_prev "            struct TransferCancelConsumer final : EventConsumer {\n                EventReactor* reactor{nullptr};\n                void ProcessEvent() override {\n                    if (reactor && reactor->GetResult() == ResultSuccess()) {\n                        reactor->SetResult(haze::ResultCancelled());\n                    }\n                }\n            };\n            Thread m_thread{};\n            UEvent m_cancel_event{};\n            UEvent m_transfer_cancel_event{};\n            TransferCancelConsumer m_transfer_cancel_consumer{};\n            EventReactor m_event_reactor{};\n\n        public:\n            explicit ConsoleMainLoop(Callback callback, int prio, int cpuid, const FsEntries& entries)\n            : m_callback{callback}, m_prio{prio}, m_cpuid{cpuid}, m_entries{entries} {\n                /* Create cancel event. */\n                ueventCreate(&m_cancel_event, false);\n                ueventCreate(&m_transfer_cancel_event, true);\n\n                /* Clear the event reactor. */\n                m_event_reactor.SetResult(ResultSuccess());\n                m_event_reactor.AddConsumer(this, waiterForUEvent(&m_cancel_event));\n                m_transfer_cancel_consumer.reactor = std::addressof(m_event_reactor);\n                m_event_reactor.AddConsumer(std::addressof(m_transfer_cancel_consumer), waiterForUEvent(&m_transfer_cancel_event));\n\n                /* Create and start thread. */\n                threadCreate(&m_thread, thread_func, this, nullptr, 1024*64, prio, cpuid);\n                threadStart(&m_thread);\n            }")
    set(cml_members_new "            struct TransferCancelConsumer final : EventConsumer {\n                EventReactor* reactor{nullptr};\n                void ProcessEvent() override {\n                    if (reactor && reactor->GetResult() == ResultSuccess()) {\n                        reactor->SetResult(haze::ResultCancelled());\n                    }\n                }\n            };\n            Thread m_thread{};\n            UEvent m_cancel_event{};\n            UEvent m_transfer_cancel_event{};\n            TransferCancelConsumer m_transfer_cancel_consumer{};\n            EventReactor m_event_reactor{};\n            std::atomic<int> m_recovery_phase{0};\n            std::atomic<u64> m_recovery_start_ns{0};\n\n        public:\n            explicit ConsoleMainLoop(Callback callback, int prio, int cpuid, const FsEntries& entries)\n            : m_callback{callback}, m_prio{prio}, m_cpuid{cpuid}, m_entries{entries} {\n                /* Create cancel event. */\n                ueventCreate(&m_cancel_event, false);\n                ueventCreate(&m_transfer_cancel_event, true);\n\n                /* Clear the event reactor. */\n                m_event_reactor.SetResult(ResultSuccess());\n                m_event_reactor.AddConsumer(this, waiterForUEvent(&m_cancel_event));\n                m_transfer_cancel_consumer.reactor = std::addressof(m_event_reactor);\n                m_event_reactor.AddConsumer(std::addressof(m_transfer_cancel_consumer), waiterForUEvent(&m_transfer_cancel_event));\n\n                /* Create and start thread. */\n                threadCreate(&m_thread, thread_func, this, nullptr, 1024*64, prio, cpuid);\n                threadStart(&m_thread);\n            }")
    string(REPLACE "${cml_members_prev}" "${cml_members_new}" src "${src}")
    string(REPLACE "${cml_members_old}" "${cml_members_new}" src "${src}")

    set(cml_fn_old "            ~ConsoleMainLoop() {\n                ueventSignal(&m_cancel_event);\n                threadWaitForExit(&m_thread);\n                threadClose(&m_thread);\n            }\n\n        public:\n            void RunApplication() {")
    set(cml_fn_prev "            ~ConsoleMainLoop() {\n                ueventSignal(&m_cancel_event);\n                threadWaitForExit(&m_thread);\n                threadClose(&m_thread);\n            }\n\n            void CancelTransfer() {\n                ueventSignal(&m_transfer_cancel_event);\n            }\n\n        public:\n            void RunApplication() {")
    set(cml_fn_new "            ~ConsoleMainLoop() {\n                m_recovery_phase.store(0, std::memory_order_release);\n                ueventSignal(&m_cancel_event);\n                threadWaitForExit(&m_thread);\n                threadClose(&m_thread);\n            }\n\n            void CancelTransfer() {\n                m_recovery_start_ns.store(armTicksToNs(armGetSystemTick()), std::memory_order_release);\n                m_recovery_phase.store(1, std::memory_order_release);\n                ueventSignal(&m_transfer_cancel_event);\n            }\n\n            bool IsRecovering() const {\n                if (!m_recovery_phase.load(std::memory_order_acquire)) {\n                    return false;\n                }\n                const u64 now = armTicksToNs(armGetSystemTick());\n                if (now >= m_recovery_start_ns.load(std::memory_order_acquire) && (now - m_recovery_start_ns.load(std::memory_order_acquire)) > 3000000000ULL) {\n                    return false;\n                }\n                return true;\n            }\n\n            void ClearRecovering() {\n                int ready = 2;\n                m_recovery_phase.compare_exchange_strong(ready, 0, std::memory_order_acq_rel);\n            }\n\n        public:\n            void RunApplication() {")
    string(REPLACE "${cml_fn_prev}" "${cml_fn_new}" src "${src}")
    string(REPLACE "${cml_fn_old}" "${cml_fn_new}" src "${src}")

    set(cml_run_old "            void RunApplication() {\n                /* Declare the object heap, to hold the database for an active session. */\n                PtpObjectHeap ptp_object_heap;\n\n                /* Configure the PTP responder. */\n                PtpResponder ptp_responder{m_callback};\n                ptp_responder.Initialize(std::addressof(m_event_reactor), std::addressof(ptp_object_heap), m_entries);\n\n                /* Ensure we maintain a clean state on exit. */\n                ON_SCOPE_EXIT {\n                    /* Finalize the PTP responder. */\n                    ptp_responder.Finalize();\n                };\n\n                /* Begin processing requests. */\n                ptp_responder.LoopProcess();\n            }")

    set(cml_run_prev "            void RunApplication() {\n                while (m_event_reactor.GetResult() != haze::ResultStopRequested()) {\n                    /* Declare the object heap, to hold the database for an active session. */\n                    PtpObjectHeap ptp_object_heap;\n\n                    /* Configure the PTP responder. */\n                    PtpResponder ptp_responder{m_callback};\n                    if (R_FAILED(ptp_responder.Initialize(std::addressof(m_event_reactor), std::addressof(ptp_object_heap), m_entries))) {\n                        break;\n                    }\n\n                    /* Ensure we maintain a clean state on exit. */\n                    ON_SCOPE_EXIT {\n                        /* Finalize the PTP responder. */\n                        ptp_responder.Finalize();\n                    };\n\n                    /* Begin processing requests. */\n                    ptp_responder.LoopProcess();\n\n                    if (m_event_reactor.GetResult() == haze::ResultStopRequested()) {\n                        break;\n                    }\n\n                    ueventClear(&m_transfer_cancel_event);\n                    if (m_event_reactor.GetResult() == haze::ResultCancelled()) {\n                        m_event_reactor.SetResult(ResultSuccess());\n                    }\n                    svcSleepThread(100000000ULL);\n                }\n            }")

    set(cml_run_v921 "            void RunApplication() {\n                while (m_event_reactor.GetResult() != haze::ResultStopRequested()) {\n                    /* Declare the object heap, to hold the database for an active session. */\n                    PtpObjectHeap ptp_object_heap;\n\n                    /* Configure the PTP responder. */\n                    PtpResponder ptp_responder{m_callback};\n                    Result init_rc = ptp_responder.Initialize(std::addressof(m_event_reactor), std::addressof(ptp_object_heap), m_entries);\n                    if (R_FAILED(init_rc)) {\n                        /* Safe cleanup of partial initialization. */\n                        ptp_responder.Finalize();\n\n                        /* Bounded recovery retries for Initialize. */\n                        constexpr int MaxInitRetries = 3;\n                        bool init_ok = false;\n                        for (int retry = 0; retry < MaxInitRetries; ++retry) {\n                            if (m_event_reactor.GetResult() == haze::ResultStopRequested()) {\n                                break;\n                            }\n                            svcSleepThread(100000000ULL);\n                            init_rc = ptp_responder.Initialize(std::addressof(m_event_reactor), std::addressof(ptp_object_heap), m_entries);\n                            if (R_SUCCEEDED(init_rc)) {\n                                init_ok = true;\n                                break;\n                            }\n                            ptp_responder.Finalize();\n                        }\n\n                        if (!init_ok) {\n                            /* Explicitly transition service to error state without hanging on Exit. */\n                            if (m_callback) {\n                                CallbackData data{CallbackType_CloseSession};\n                                m_callback(&data);\n                            }\n                            s32 waiter_idx = -1;\n                            m_event_reactor.WaitFor(std::addressof(waiter_idx), waiterForUEvent(&m_cancel_event));\n                            break;\n                        }\n                    }\n\n                    /* Run request processing loop. */\n                    const Result loop_rc = ptp_responder.LoopProcess();\n\n                    /* Normal stop requested or focus lost: finalize and exit immediately. */\n                    if (m_event_reactor.GetResult() == haze::ResultStopRequested() || loop_rc == haze::ResultStopRequested() || loop_rc == haze::ResultFocusLost()) {\n                        ptp_responder.Finalize();\n                        break;\n                    }\n\n                    /* Only recover USB after a broken transport caused by local cancellation. */\n                    const bool local_cancel = ptp_responder.IsCancelled();\n\n                    if (!ptp_responder.IsBroken() || !local_cancel) {\n                        /* Preserve previous behavior for other exit reasons. */\n                        ptp_responder.Finalize();\n                        break;\n                    }\n\n                    /* 1. Finalize previous USB session FIRST to disconnect from host. */\n                    ptp_responder.Finalize();\n\n                    /* 2. Clear cancellation state before re-enumeration. */\n                    ueventClear(&m_transfer_cancel_event);\n                    if (m_event_reactor.GetResult() == haze::ResultCancelled()) {\n                        m_event_reactor.SetResult(ResultSuccess());\n                    }\n\n                    /* 3. 100 ms delay while detached to allow host re-enumeration settling. */\n                    svcSleepThread(100000000ULL);\n\n                    /* 4. Check stop request before loop re-enters Initialize. */\n                    if (m_event_reactor.GetResult() == haze::ResultStopRequested()) {\n                        break;\n                    }\n                }\n            }")

    set(cml_run_new "            void RunApplication() {\n                while (m_event_reactor.GetResult() != haze::ResultStopRequested()) {\n                    /* Declare the object heap, to hold the database for an active session. */\n                    PtpObjectHeap ptp_object_heap;\n\n                    /* Configure the PTP responder. */\n                    PtpResponder ptp_responder{m_callback};\n                    Result init_rc = ptp_responder.Initialize(std::addressof(m_event_reactor), std::addressof(ptp_object_heap), m_entries);\n                    if (R_SUCCEEDED(init_rc) && m_recovery_phase.load(std::memory_order_acquire) == 1) {\n                        m_recovery_phase.store(2, std::memory_order_release);\n                    }\n                    if (R_FAILED(init_rc)) {\n                        /* Safe cleanup of partial initialization. */\n                        ptp_responder.Finalize();\n\n                        /* Bounded recovery retries for Initialize. */\n                        constexpr int MaxInitRetries = 3;\n                        bool init_ok = false;\n                        for (int retry = 0; retry < MaxInitRetries; ++retry) {\n                            if (m_event_reactor.GetResult() == haze::ResultStopRequested()) {\n                                break;\n                            }\n                            svcSleepThread(100000000ULL);\n                            init_rc = ptp_responder.Initialize(std::addressof(m_event_reactor), std::addressof(ptp_object_heap), m_entries);\n                            if (R_SUCCEEDED(init_rc)) {\n                                if (m_recovery_phase.load(std::memory_order_acquire) == 1) {\n                                    m_recovery_phase.store(2, std::memory_order_release);\n                                }\n                                init_ok = true;\n                                break;\n                            }\n                            ptp_responder.Finalize();\n                        }\n\n                        if (!init_ok) {\n                            m_recovery_phase.store(0, std::memory_order_release);\n                            /* Explicitly transition service to error state without hanging on Exit. */\n                            if (m_callback) {\n                                CallbackData data{CallbackType_CloseSession};\n                                m_callback(&data);\n                            }\n                            s32 waiter_idx = -1;\n                            m_event_reactor.WaitFor(std::addressof(waiter_idx), waiterForUEvent(&m_cancel_event));\n                            break;\n                        }\n                    }\n\n                    /* Run request processing loop. */\n                    const Result loop_rc = ptp_responder.LoopProcess();\n\n                    /* Normal stop requested or focus lost: finalize and exit immediately. */\n                    if (m_event_reactor.GetResult() == haze::ResultStopRequested() || loop_rc == haze::ResultStopRequested() || loop_rc == haze::ResultFocusLost()) {\n                        m_recovery_phase.store(0, std::memory_order_release);\n                        ptp_responder.Finalize();\n                        break;\n                    }\n\n                    /* Only recover USB after a broken transport caused by local cancellation. */\n                    const bool local_cancel = ptp_responder.IsCancelled();\n\n                    if (!ptp_responder.IsBroken() || !local_cancel) {\n                        /* Preserve previous behavior for other exit reasons. */\n                        m_recovery_phase.store(0, std::memory_order_release);\n                        ptp_responder.Finalize();\n                        break;\n                    }\n\n                    /* 1. Mark recovering before finalizing previous USB session. */\n                    m_recovery_start_ns.store(armTicksToNs(armGetSystemTick()), std::memory_order_release);\n                    m_recovery_phase.store(1, std::memory_order_release);\n\n                    /* 2. Finalize previous USB session FIRST to disconnect from host. */\n                    ptp_responder.Finalize();\n\n                    /* 3. Clear cancellation state before re-enumeration. */\n                    ueventClear(&m_transfer_cancel_event);\n                    if (m_event_reactor.GetResult() == haze::ResultCancelled()) {\n                        m_event_reactor.SetResult(ResultSuccess());\n                    }\n\n                    /* 4. 100 ms delay while detached to allow host re-enumeration settling. */\n                    svcSleepThread(100000000ULL);\n\n                    /* 5. Check stop request before loop re-enters Initialize. */\n                    if (m_event_reactor.GetResult() == haze::ResultStopRequested()) {\n                        m_recovery_phase.store(0, std::memory_order_release);\n                        break;\n                    }\n                }\n            }")

    string(REPLACE "loop_rc == haze::ResultFocusLost)" "loop_rc == haze::ResultFocusLost())" src "${src}")
    string(REPLACE "${cml_run_v921}" "${cml_run_new}" src "${src}")
    string(REPLACE "${cml_run_prev}" "${cml_run_new}" src "${src}")
    string(REPLACE "${cml_run_old}" "${cml_run_new}" src "${src}")

    string(FIND "${src}" "m_transfer_cancel_event" find_cancel_event)
    string(FIND "${src}" "void CancelTransfer()" find_cancel_fn)
    string(FIND "${src}" "bool IsRecovering() const" find_is_recovering_fn)
    string(FIND "${src}" "void ClearRecovering()" find_clear_recovering_fn)
    string(FIND "${src}" "MaxInitRetries" find_cml_retries)
    string(FIND "${src}" "local_cancel" find_cml_local_cancel)
    string(FIND "${src}" "loop_rc == haze::ResultFocusLost()" find_cml_focus)
    string(FIND "${src}" "void ClearTransferCancel()" find_clear_fn)
    if(NOT find_cancel_event EQUAL -1 AND NOT find_cancel_fn EQUAL -1 AND NOT find_is_recovering_fn EQUAL -1 AND NOT find_clear_recovering_fn EQUAL -1 AND NOT find_cml_retries EQUAL -1 AND NOT find_cml_local_cancel EQUAL -1 AND NOT find_cml_focus EQUAL -1 AND find_clear_fn EQUAL -1)
        file(WRITE "include/haze/console_main_loop.hpp" "${src}")
        message(STATUS "[libhaze-patch] console_main_loop.hpp already patched")
    else()
        set(cml_members_old "            Thread m_thread{};\n            UEvent m_cancel_event{};\n            EventReactor m_event_reactor{};\n\n        public:\n            explicit ConsoleMainLoop(Callback callback, int prio, int cpuid, const FsEntries& entries)\n            : m_callback{callback}, m_prio{prio}, m_cpuid{cpuid}, m_entries{entries} {\n                /* Create cancel event. */\n                ueventCreate(&m_cancel_event, false);\n\n                /* Clear the event reactor. */\n                m_event_reactor.SetResult(ResultSuccess());\n                m_event_reactor.AddConsumer(this, waiterForUEvent(&m_cancel_event));\n\n                /* Create and start thread. */\n                threadCreate(&m_thread, thread_func, this, nullptr, 1024*64, prio, cpuid);\n                threadStart(&m_thread);\n            }")
        string(REPLACE "${cml_members_old}" "${cml_members_new}" src "${src}")

        set(cml_fn_old "            ~ConsoleMainLoop() {\n                ueventSignal(&m_cancel_event);\n                threadWaitForExit(&m_thread);\n                threadClose(&m_thread);\n            }\n\n        public:\n            void RunApplication() {")
        string(REPLACE "${cml_fn_old}" "${cml_fn_new}" src "${src}")
        string(REPLACE "loop_rc == haze::ResultFocusLost)" "loop_rc == haze::ResultFocusLost())" src "${src}")
        string(REPLACE "${cml_run_v921}" "${cml_run_new}" src "${src}")
        string(REPLACE "${cml_run_prev}" "${cml_run_new}" src "${src}")
        string(REPLACE "${cml_run_old}" "${cml_run_new}" src "${src}")

        string(FIND "${src}" "m_transfer_cancel_event" find_cancel_event_after)
        string(FIND "${src}" "void CancelTransfer()" find_cancel_fn_after)
        string(FIND "${src}" "bool IsRecovering() const" find_is_recovering_fn_after)
        string(FIND "${src}" "void ClearRecovering()" find_clear_recovering_fn_after)
        string(FIND "${src}" "MaxInitRetries" find_cml_retries_after)
        string(FIND "${src}" "local_cancel" find_cml_local_cancel_after)
        string(FIND "${src}" "loop_rc == haze::ResultFocusLost()" find_cml_focus_after)
        string(FIND "${src}" "void ClearTransferCancel()" find_clear_fn_after)
        if(find_cancel_event_after EQUAL -1 OR find_cancel_fn_after EQUAL -1 OR find_is_recovering_fn_after EQUAL -1 OR find_clear_recovering_fn_after EQUAL -1 OR find_cml_retries_after EQUAL -1 OR find_cml_local_cancel_after EQUAL -1 OR find_cml_focus_after EQUAL -1 OR NOT find_clear_fn_after EQUAL -1)
            message(FATAL_ERROR "[libhaze-patch] failed to apply cancel patch to console_main_loop.hpp")
        endif()
        file(WRITE "include/haze/console_main_loop.hpp" "${src}")
        message(STATUS "[libhaze-patch] applied console_main_loop.hpp cancel patch")
    endif()
else()
    message(FATAL_ERROR "[libhaze-patch] include/haze/console_main_loop.hpp not found")
endif()

# --- 13. source/haze.cpp : CancelTransfer (deadlock-free Exit) ---------------
if(EXISTS "source/haze.cpp")
    file(READ "source/haze.cpp" src)
    set(haze_cpp_prev "void Exit() {\n    std::scoped_lock lock{g_mutex};\n    if (!g_haze) {\n        return;\n    }\n\n    /* this will block until thread exit. */\n    g_haze.reset();\n}\n\nvoid CancelTransfer() {\n    std::scoped_lock lock{g_mutex};\n    if (g_haze) {\n        g_haze->CancelTransfer();\n    }\n}\n\nvoid ClearTransferCancel() {\n    std::scoped_lock lock{g_mutex};\n    if (g_haze) {\n        g_haze->ClearTransferCancel();\n    }\n}\n\n} // namespace haze")
    set(haze_cpp_v921 "void Exit() {\n    std::unique_ptr<haze::ConsoleMainLoop> haze_to_destroy;\n    {\n        std::scoped_lock lock{g_mutex};\n        if (!g_haze) {\n            return;\n        }\n\n        /* move instance so g_mutex is released before blocking on thread exit. */\n        haze_to_destroy = std::move(g_haze);\n    }\n}\n\nvoid CancelTransfer() {\n    std::scoped_lock lock{g_mutex};\n    if (g_haze) {\n        g_haze->CancelTransfer();\n    }\n}\n\n} // namespace haze")
    set(haze_cpp_target "void Exit() {\n    std::unique_ptr<haze::ConsoleMainLoop> haze_to_destroy;\n    {\n        std::scoped_lock lock{g_mutex};\n        if (!g_haze) {\n            return;\n        }\n\n        /* move instance so g_mutex is released before blocking on thread exit. */\n        haze_to_destroy = std::move(g_haze);\n    }\n}\n\nvoid CancelTransfer() {\n    std::scoped_lock lock{g_mutex};\n    if (g_haze) {\n        g_haze->CancelTransfer();\n    }\n}\n\nbool IsRecovering() {\n    std::scoped_lock lock{g_mutex};\n    return g_haze && g_haze->IsRecovering();\n}\n\nvoid ClearRecovering() {\n    std::scoped_lock lock{g_mutex};\n    if (g_haze) {\n        g_haze->ClearRecovering();\n    }\n}\n\n} // namespace haze")
    string(REPLACE "${haze_cpp_prev}" "${haze_cpp_target}" src "${src}")
    string(REPLACE "${haze_cpp_v921}" "${haze_cpp_target}" src "${src}")

    string(FIND "${src}" "void CancelTransfer()" find_cancel_impl)
    string(FIND "${src}" "bool IsRecovering()" find_is_recovering_impl)
    string(FIND "${src}" "void ClearRecovering()" find_clear_recovering_impl)
    string(FIND "${src}" "haze_to_destroy = std::move(g_haze);" find_exit_move)
    string(FIND "${src}" "void ClearTransferCancel()" find_clear_impl)
    if(NOT find_cancel_impl EQUAL -1 AND NOT find_is_recovering_impl EQUAL -1 AND NOT find_clear_recovering_impl EQUAL -1 AND NOT find_exit_move EQUAL -1 AND find_clear_impl EQUAL -1)
        file(WRITE "source/haze.cpp" "${src}")
        message(STATUS "[libhaze-patch] haze.cpp cancel already patched")
    else()
        set(haze_cpp_old "void Exit() {\n    std::scoped_lock lock{g_mutex};\n    if (!g_haze) {\n        return;\n    }\n\n    /* this will block until thread exit. */\n    g_haze.reset();\n}\n\n} // namespace haze")
        string(REPLACE "${haze_cpp_old}" "${haze_cpp_target}" src "${src}")
        string(FIND "${src}" "void CancelTransfer()" find_cancel_impl_after)
        string(FIND "${src}" "bool IsRecovering()" find_is_recovering_impl_after)
        string(FIND "${src}" "void ClearRecovering()" find_clear_recovering_impl_after)
        string(FIND "${src}" "haze_to_destroy = std::move(g_haze);" find_exit_move_after)
        string(FIND "${src}" "void ClearTransferCancel()" find_clear_impl_after)
        if(find_cancel_impl_after EQUAL -1 OR find_is_recovering_impl_after EQUAL -1 OR find_clear_recovering_impl_after EQUAL -1 OR find_exit_move_after EQUAL -1 OR NOT find_clear_impl_after EQUAL -1)
            message(FATAL_ERROR "[libhaze-patch] failed to apply CancelTransfer patch to haze.cpp")
        endif()
        file(WRITE "source/haze.cpp" "${src}")
        message(STATUS "[libhaze-patch] applied haze.cpp CancelTransfer patch")
    endif()
else()
    message(FATAL_ERROR "[libhaze-patch] source/haze.cpp not found")
endif()

# --- 14. include/haze/ptp_responder.hpp : m_reactor & WriteCallbackFile aborted
if(EXISTS "include/haze/ptp_responder.hpp")
    file(READ "include/haze/ptp_responder.hpp" src)
    string(FIND "${src}" "EventReactor *m_reactor" find_reactor)
    string(FIND "${src}" "bool aborted = false" find_aborted_param)
    string(FIND "${src}" "bool IsBroken() const" find_is_broken)
    if(NOT find_reactor EQUAL -1 AND NOT find_aborted_param EQUAL -1 AND NOT find_is_broken EQUAL -1)
        message(STATUS "[libhaze-patch] ptp_responder.hpp cancel already patched")
    else()
        set(resp_h_members_old "        private:\n            Callback m_callback;\n            AsyncUsbServer m_usb_server;\n            std::vector<FsEntry> m_fs_entries;")
        set(resp_h_members_new "        private:\n            Callback m_callback;\n            AsyncUsbServer m_usb_server;\n            EventReactor *m_reactor{nullptr};\n            std::vector<FsEntry> m_fs_entries;")
        string(REPLACE "${resp_h_members_old}" "${resp_h_members_new}" src "${src}")

        set(resp_h_cb_old "            void WriteCallbackSession(CallbackType type);\n            void WriteCallbackFile(CallbackType type, const char* name);\n            void WriteCallbackRename(CallbackType type, const char* name, const char* newname);")
        set(resp_h_cb_new "            void WriteCallbackSession(CallbackType type);\n            void WriteCallbackFile(CallbackType type, const char* name, bool aborted = false);\n            void WriteCallbackRename(CallbackType type, const char* name, const char* newname);")
        string(REPLACE "${resp_h_cb_old}" "${resp_h_cb_new}" src "${src}")

        set(resp_h_methods_old "            Result Initialize(EventReactor *reactor, PtpObjectHeap *object_heap, const FsEntries& entries);\n            void Finalize();\n        public:\n            Result LoopProcess();")
        set(resp_h_methods_new "            Result Initialize(EventReactor *reactor, PtpObjectHeap *object_heap, const FsEntries& entries);\n            void Finalize();\n            bool IsBroken() const { return m_usb_server.IsBroken(); }\n            bool IsCancelled() const { return m_usb_server.IsCancelled(); }\n        public:\n            Result LoopProcess();")
        string(REPLACE "${resp_h_methods_old}" "${resp_h_methods_new}" src "${src}")

        string(FIND "${src}" "EventReactor *m_reactor" find_reactor_after)
        string(FIND "${src}" "bool aborted = false" find_aborted_param_after)
        string(FIND "${src}" "bool IsBroken() const" find_is_broken_after)
        if(find_reactor_after EQUAL -1 OR find_aborted_param_after EQUAL -1 OR find_is_broken_after EQUAL -1)
            message(FATAL_ERROR "[libhaze-patch] failed to apply cancel patch to ptp_responder.hpp")
        endif()
        file(WRITE "include/haze/ptp_responder.hpp" "${src}")
        message(STATUS "[libhaze-patch] applied ptp_responder.hpp cancel patch")
    endif()
else()
    message(FATAL_ERROR "[libhaze-patch] include/haze/ptp_responder.hpp not found")
endif()

# --- 15. source/ptp_responder.cpp : HandleRequest & WriteCallbackFile --------
if(EXISTS "source/ptp_responder.cpp")
    file(READ "source/ptp_responder.cpp" src)

    string(FIND "${src}" "failed to send cancel response" find_log_cancel)
    string(FIND "${src}" "m_usb_server.IsBroken()" find_loop_broken)
    string(FIND "${src}" "if (m_usb_server.IsBroken()) {\n                    R_THROW(haze::ResultTransferFailed());" find_guard_broken)
    if(NOT find_log_cancel EQUAL -1 AND NOT find_loop_broken EQUAL -1 AND NOT find_guard_broken EQUAL -1)
        message(STATUS "[libhaze-patch] ptp_responder.cpp cancel already patched")
    else()
        string(FIND "${src}" "void log_write(" find_lw)
        if(find_lw EQUAL -1)
            set(resp_incl_old "#include <haze/ptp_responder_types.hpp>")
            set(resp_incl_new "#include <haze/ptp_responder_types.hpp>\n\nextern \"C\" {\n    __attribute__((weak)) void log_write(const char* s, ...) {}\n}")
            string(REPLACE "${resp_incl_old}" "${resp_incl_new}" src "${src}")
        endif()

        set(resp_cpp_loop_old "                R_CATCH_ALL() {\n                    /* On other failures, try to handle another request. */\n                    continue;\n                }")
        set(resp_cpp_loop_new "                R_CATCH_ALL() {\n                    /* sphaira: terminate transport loop on broken endpoint or stop request */\n                    if (m_usb_server.IsBroken() || (m_reactor && m_reactor->GetResult() == haze::ResultStopRequested())) {\n                        R_THROW(R_CURRENT_RESULT);\n                    }\n                    /* On other failures, try to handle another request. */\n                    continue;\n                }")
        string(REPLACE "${resp_cpp_loop_old}" "${resp_cpp_loop_new}" src "${src}")

        set(resp_cpp_init_old "    Result PtpResponder::Initialize(EventReactor *reactor, PtpObjectHeap *object_heap, const FsEntries& entries) {\n        m_object_heap = object_heap;")
        set(resp_cpp_init_new "    Result PtpResponder::Initialize(EventReactor *reactor, PtpObjectHeap *object_heap, const FsEntries& entries) {\n        m_reactor = reactor;\n        m_object_heap = object_heap;")
        string(REPLACE "${resp_cpp_init_old}" "${resp_cpp_init_new}" src "${src}")

        string(REPLACE "        R_TRY_CATCH(this->HandleRequestImpl()) {\n        R_TRY_CATCH(this->HandleRequestImpl()) {" "        R_TRY_CATCH(this->HandleRequestImpl()) {" src "${src}")
        string(REPLACE "            R_CATCH(haze::ResultUnknownRequestType) {\n            R_CATCH(haze::ResultUnknownRequestType) {" "            R_CATCH(haze::ResultUnknownRequestType) {" src "${src}")

        set(resp_cpp_catch_cancel_new "            R_CATCH(haze::ResultCancelled) {\n                if (m_reactor && m_reactor->GetResult() == haze::ResultCancelled()) {\n                    m_reactor->SetResult(ResultSuccess());\n                }\n                if (m_usb_server.IsBroken()) {\n                    R_THROW(haze::ResultTransferFailed());\n                }\n                const Result resp_rc = this->WriteResponse(PtpResponseCode_TransactionCanceled);\n                if (R_SUCCEEDED(resp_rc)) {\n                    log_write(\"[LIBHAZE] cancelled transaction completed (0x%04X)\\n\", PtpResponseCode_TransactionCanceled);\n                } else {\n                    log_write(\"[LIBHAZE] failed to send cancel response: 0x%08X\\n\", resp_rc.GetValue());\n                }\n                R_TRY(resp_rc);\n            }")

        set(resp_cpp_handle_old "        R_TRY_CATCH(this->HandleRequestImpl()) {\n            R_CATCH(haze::ResultUnknownRequestType) {")
        set(resp_cpp_handle_new "        R_TRY_CATCH(this->HandleRequestImpl()) {\n${resp_cpp_catch_cancel_new}\n            R_CATCH(haze::ResultUnknownRequestType) {")
        string(REPLACE "${resp_cpp_handle_old}" "${resp_cpp_handle_new}" src "${src}")

        set(resp_cpp_handle_prev "            R_CATCH(haze::ResultCancelled) {\n                if (m_reactor && m_reactor->GetResult() == haze::ResultCancelled()) {\n                    m_reactor->SetResult(ResultSuccess());\n                }\n                const Result resp_rc = this->WriteResponse(PtpResponseCode_TransactionCanceled);\n                if (R_SUCCEEDED(resp_rc)) {\n                    log_write(\"[LIBHAZE] cancelled transaction completed (0x%04X)\\n\", PtpResponseCode_TransactionCanceled);\n                } else {\n                    log_write(\"[LIBHAZE] failed to send cancel response: 0x%08X\\n\", resp_rc.GetValue());\n                }\n                R_TRY(resp_rc);\n            }")
        string(REPLACE "${resp_cpp_handle_prev}" "${resp_cpp_catch_cancel_new}" src "${src}")

        set(resp_cpp_handle_prev2 "            R_CATCH(haze::ResultCancelled) {\n                if (m_reactor && m_reactor->GetResult() == haze::ResultCancelled()) {\n                    m_reactor->SetResult(ResultSuccess());\n                }\n                log_write(\"[LIBHAZE] cancelled transaction completed (0x%04X)\\n\", PtpResponseCode_TransactionCanceled);\n                R_TRY(this->WriteResponse(PtpResponseCode_TransactionCanceled));\n            }")
        string(REPLACE "${resp_cpp_handle_prev2}" "${resp_cpp_catch_cancel_new}" src "${src}")

        set(resp_cpp_handle_prev3 "            R_CATCH(haze::ResultCancelled) {\n                if (m_reactor && m_reactor->GetResult() == haze::ResultCancelled()) {\n                    m_reactor->SetResult(ResultSuccess());\n                }\n                R_TRY(this->WriteResponse(PtpResponseCode_TransactionCanceled));\n            }")
        string(REPLACE "${resp_cpp_handle_prev3}" "${resp_cpp_catch_cancel_new}" src "${src}")

        set(resp_cpp_cb_old "    void PtpResponder::WriteCallbackFile(CallbackType type, const char* name) {\n        if (!m_callback) {\n            return;\n        }\n        CallbackData data{type};\n        std::strncpy(data.file.filename, FixName(name), sizeof(data.file.filename)-1);\n        m_callback(&data);\n    }")
        set(resp_cpp_cb_new "    void PtpResponder::WriteCallbackFile(CallbackType type, const char* name, bool aborted) {\n        if (!m_callback) {\n            return;\n        }\n        CallbackData data{type};\n        std::strncpy(data.file.filename, FixName(name), sizeof(data.file.filename)-1);\n        data.file.aborted = aborted;\n        m_callback(&data);\n    }")
        string(REPLACE "${resp_cpp_cb_old}" "${resp_cpp_cb_new}" src "${src}")

        string(FIND "${src}" "m_reactor = reactor;" find_init_reactor_after)
        string(FIND "${src}" "m_reactor->GetResult() == haze::ResultCancelled()" find_guard_reactor_after)
        string(FIND "${src}" "PtpResponseCode_TransactionCanceled" find_trans_cancel_after)
        string(FIND "${src}" "data.file.aborted = aborted;" find_data_aborted_after)
        string(FIND "${src}" "failed to send cancel response" find_log_cancel_after)
        string(FIND "${src}" "m_usb_server.IsBroken()" find_loop_broken_after)
        string(FIND "${src}" "if (m_usb_server.IsBroken()) {\n                    R_THROW(haze::ResultTransferFailed());" find_guard_broken_after)
        if(find_init_reactor_after EQUAL -1 OR find_guard_reactor_after EQUAL -1 OR find_trans_cancel_after EQUAL -1 OR find_data_aborted_after EQUAL -1 OR find_log_cancel_after EQUAL -1 OR find_loop_broken_after EQUAL -1 OR find_guard_broken_after EQUAL -1)
            message(FATAL_ERROR "[libhaze-patch] failed to apply cancel patch to ptp_responder.cpp")
        endif()
        file(WRITE "source/ptp_responder.cpp" "${src}")
        message(STATUS "[libhaze-patch] applied ptp_responder.cpp cancel patch")
    endif()
else()
    message(FATAL_ERROR "[libhaze-patch] source/ptp_responder.cpp not found")
endif()

# --- 16. include/haze/usb_session.hpp & source/usb_session.cpp : CancelEndpoint ---
if(EXISTS "include/haze/usb_session.hpp")
    file(READ "include/haze/usb_session.hpp" h_src)
    string(FIND "${h_src}" "CancelEndpoint" find_ce_decl)
    if(find_ce_decl EQUAL -1)
        set(usb_h_old "            Result GetTransferResult(UsbSessionEndpoint ep, u32 urb_id, u32 *out_transferred_size);")
        set(usb_h_new "            Result GetTransferResult(UsbSessionEndpoint ep, u32 urb_id, u32 *out_transferred_size);\n            Result CancelEndpoint(UsbSessionEndpoint ep, u32 urb_id);")
        string(REPLACE "${usb_h_old}" "${usb_h_new}" h_src "${h_src}")
        string(FIND "${h_src}" "CancelEndpoint" find_ce_decl_after)
        if(find_ce_decl_after EQUAL -1)
            message(FATAL_ERROR "[libhaze-patch] failed to apply CancelEndpoint to usb_session.hpp")
        endif()
        file(WRITE "include/haze/usb_session.hpp" "${h_src}")
        message(STATUS "[libhaze-patch] applied usb_session.hpp CancelEndpoint patch")
    else()
        message(STATUS "[libhaze-patch] usb_session.hpp CancelEndpoint already patched")
    endif()
else()
    message(FATAL_ERROR "[libhaze-patch] include/haze/usb_session.hpp not found")
endif()

if(EXISTS "source/usb_session.cpp")
    file(READ "source/usb_session.cpp" src)

    set(single_ce "    Result UsbSession::CancelEndpoint(UsbSessionEndpoint ep, u32 urb_id) {\n        R_UNLESS(m_endpoints[ep], haze::ResultInvalidArgument());\n\n        /* Request hardware cancellation of in-flight URBs on endpoint. */\n        R_TRY(usbDsEndpoint_Cancel(m_endpoints[ep]));\n\n        /* Wait for driver to signal completion event after cancel (bounded to 1s). */\n        R_TRY(eventWait(std::addressof(m_endpoints[ep]->CompletionEvent), 1000000000ULL));\n\n        /* Harvest report to ensure URB retirement and clear endpoint completion state. */\n        u32 transferred = 0;\n        const Result res = this->GetTransferResult(ep, urb_id, std::addressof(transferred));\n        if (res == haze::ResultCancelled() || R_SUCCEEDED(res)) {\n            R_SUCCEED();\n        }\n\n        R_RETURN(res);\n    }")
    set(dup_ce "${single_ce}\n\n${single_ce}")
    string(FIND "${src}" "${dup_ce}" find_dup_ce)
    if(NOT find_dup_ce EQUAL -1)
        string(REPLACE "${dup_ce}" "${single_ce}" src "${src}")
        file(WRITE "source/usb_session.cpp" "${src}")
    endif()

    string(FIND "${src}" "parse_res == 0x748C" find_urb_cancel)
    string(FIND "${src}" "res == haze::ResultCancelled() || R_SUCCEEDED(res)" find_ce_verified)
    string(FIND "${src}" "${dup_ce}" find_dup_after_clean)
    if(NOT find_urb_cancel EQUAL -1 AND NOT find_ce_verified EQUAL -1 AND find_dup_after_clean EQUAL -1)
        message(STATUS "[libhaze-patch] usb_session.cpp cancel already patched")
    else()
        set(usb_sess_old "    Result UsbSession::GetTransferResult(UsbSessionEndpoint ep, u32 urb_id, u32 *out_transferred_size) {\n        UsbDsReportData report_data;\n\n        R_TRY(eventClear(std::addressof(m_endpoints[ep]->CompletionEvent)));\n        R_TRY(usbDsEndpoint_GetReportData(m_endpoints[ep], std::addressof(report_data)));\n        R_TRY(usbDsParseReportData(std::addressof(report_data), urb_id, nullptr, out_transferred_size));\n\n        R_SUCCEED();\n    }")
        set(usb_sess_prev "    Result UsbSession::GetTransferResult(UsbSessionEndpoint ep, u32 urb_id, u32 *out_transferred_size) {\n        UsbDsReportData report_data;\n\n        R_TRY(eventClear(std::addressof(m_endpoints[ep]->CompletionEvent)));\n        R_TRY(usbDsEndpoint_GetReportData(m_endpoints[ep], std::addressof(report_data)));\n        const Result parse_res = usbDsParseReportData(std::addressof(report_data), urb_id, nullptr, out_transferred_size);\n        if (parse_res == 0x748C) {\n            R_THROW(haze::ResultCancelled());\n        }\n        R_RETURN(parse_res);\n    }")
        set(usb_sess_prev2 "    Result UsbSession::GetTransferResult(UsbSessionEndpoint ep, u32 urb_id, u32 *out_transferred_size) {\n        UsbDsReportData report_data;\n\n        R_TRY(eventClear(std::addressof(m_endpoints[ep]->CompletionEvent)));\n        R_TRY(usbDsEndpoint_GetReportData(m_endpoints[ep], std::addressof(report_data)));\n        const Result parse_res = usbDsParseReportData(std::addressof(report_data), urb_id, nullptr, out_transferred_size);\n        if (parse_res == 0x748C) {\n            R_THROW(haze::ResultCancelled());\n        }\n        R_RETURN(parse_res);\n    }\n\n    Result UsbSession::CancelEndpoint(UsbSessionEndpoint ep, u32 urb_id) {\n        if (!m_endpoints[ep]) {\n            R_SUCCEED();\n        }\n        usbDsEndpoint_Cancel(m_endpoints[ep]);\n        eventWait(std::addressof(m_endpoints[ep]->CompletionEvent), 1000000000ULL);\n        u32 transferred = 0;\n        this->GetTransferResult(ep, urb_id, std::addressof(transferred));\n        R_SUCCEED();\n    }")

        set(usb_sess_new "    Result UsbSession::GetTransferResult(UsbSessionEndpoint ep, u32 urb_id, u32 *out_transferred_size) {\n        UsbDsReportData report_data;\n\n        R_TRY(eventClear(std::addressof(m_endpoints[ep]->CompletionEvent)));\n        R_TRY(usbDsEndpoint_GetReportData(m_endpoints[ep], std::addressof(report_data)));\n        const Result parse_res = usbDsParseReportData(std::addressof(report_data), urb_id, nullptr, out_transferred_size);\n        if (parse_res == 0x748C) {\n            R_THROW(haze::ResultCancelled());\n        }\n        R_RETURN(parse_res);\n    }\n\n    Result UsbSession::CancelEndpoint(UsbSessionEndpoint ep, u32 urb_id) {\n        R_UNLESS(m_endpoints[ep], haze::ResultInvalidArgument());\n\n        /* Request hardware cancellation of in-flight URBs on endpoint. */\n        R_TRY(usbDsEndpoint_Cancel(m_endpoints[ep]));\n\n        /* Wait for driver to signal completion event after cancel (bounded to 1s). */\n        R_TRY(eventWait(std::addressof(m_endpoints[ep]->CompletionEvent), 1000000000ULL));\n\n        /* Harvest report to ensure URB retirement and clear endpoint completion state. */\n        u32 transferred = 0;\n        const Result res = this->GetTransferResult(ep, urb_id, std::addressof(transferred));\n        if (res == haze::ResultCancelled() || R_SUCCEEDED(res)) {\n            R_SUCCEED();\n        }\n\n        R_RETURN(res);\n    }")

        string(FIND "${src}" "${usb_sess_prev2}" find_prev2)
        string(FIND "${src}" "${usb_sess_prev}" find_prev)
        if(NOT find_prev2 EQUAL -1)
            string(REPLACE "${usb_sess_prev2}" "${usb_sess_new}" src "${src}")
        elseif(NOT find_prev EQUAL -1)
            string(REPLACE "${usb_sess_prev}" "${usb_sess_new}" src "${src}")
        else()
            string(REPLACE "${usb_sess_old}" "${usb_sess_new}" src "${src}")
        endif()

        string(FIND "${src}" "parse_res == 0x748C" find_urb_cancel_after)
        string(FIND "${src}" "res == haze::ResultCancelled() || R_SUCCEEDED(res)" find_ce_after)
        string(FIND "${src}" "${dup_ce}" find_dup_final)
        if(find_urb_cancel_after EQUAL -1 OR find_ce_after EQUAL -1 OR NOT find_dup_final EQUAL -1)
            message(FATAL_ERROR "[libhaze-patch] failed to apply cancel patch to usb_session.cpp")
        endif()
        file(WRITE "source/usb_session.cpp" "${src}")
        message(STATUS "[libhaze-patch] applied usb_session.cpp cancel patch")
    endif()
else()
    message(FATAL_ERROR "[libhaze-patch] source/usb_session.cpp not found")
endif()

include("${CMAKE_CURRENT_LIST_DIR}/patch_libhaze_cleanup.cmake")
